name: iac-dispatch
on:
  workflow_dispatch:
    inputs:
      environment: { type: choice, options: [DEV,UAT,PROD], required: true }
      branch: { type: string, default: main, required: true }
      action: { type: choice, options: [validate,plan,plan-apply,destroy-plan,destroy-apply], required: true }
      tf_lock_id: { type: string, required: false }
      tf_import_id: { type: string, required: false }
      tf_import_name: { type: string, required: false }
      tf_remove_name: { type: string, required: false }
      tf_use_extra_args: { type: boolean, default: false }

jobs:
  validate:
    if: ${{ inputs.action == 'validate' }}
    uses: ./.github/workflows/terraform-validate.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
  plan:
    if: ${{ inputs.action == 'plan' || inputs.action == 'plan-apply' }}
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: ${{ inputs.environment }}
      tf_use_extra_args: ${{ inputs.tf_use_extra_args }}
    secrets: inherit
  apply:
    if: ${{ inputs.action == 'plan-apply' }}
    needs: [plan]
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
  destroy-plan:
    if: ${{ inputs.action == 'destroy-plan' || inputs.action == 'destroy-apply' }}
    uses: ./.github/workflows/terraform-destroy-plan.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
  destroy-apply:
    if: ${{ inputs.action == 'destroy-apply' }}
    needs: [destroy-plan]
    uses: ./.github/workflows/terraform-destroy-apply.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
